<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEcx5v1r\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEcx5v1r/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEcx5v1r.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEcx5v1r\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEcx5v1r\appProdProjectContainer([
    'container.build_hash' => 'Ecx5v1r',
    'container.build_id' => '320ca23b',
    'container.build_time' => 1688934815,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEcx5v1r');
